[package]
name = "haste-leader"
version = "0.1.0"
authors = ["wayslog <zxs867179@gmail.com>"]
edition = "2018"

[[bin]]
name="leader"
path="src/main.rs"

[dependencies]
haste-core = { path = "../haste-core" }
