[package]
name = "haste-core"
version = "0.1.0"
authors = ["wayslog <zxs867179@gmail.com>"]
edition = "2018"

[lib]
name="haste_core"
path="src/lib.rs"

[dependencies]
haste-info = { path = "../haste-info" }